.\" Manpage for aitshal
.\" Author of this manpage is Aitzaz Imtiaz <aitzazimtiaz.ai@gmail.com>, contact him to correct errors or typos.
.\" This man page is released into the public domain by B-Consortium under B-License and Freedom to Public Access
.TH aitshal 6 "25 June 2023" "1.0" "aitshal User Manual"
.SH NAME
aitshal \- aitshal
.SH DESCRIPTION
This command works only on B-Consortium repositories where the repository specifies the use of aitshal is supported,
however any B-Consortium project can be cloned via this, but installation will pass an error.
.PP
Installation and downloading of C-styled repositories which are aitshal supported
.SH AUTHOR
Aitzaz Imtiaz ( https://github.com/AitzazImtiaz )
.SH COPYRIGHT
aitshal was made by B-Consortium under the philosophy that public access and development be encouraged due to which
the consortium passed its own B-License which allows anyone to copy this work without necessary attributions.
